// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/v59.0/_middleware.ts";
import * as $1 from "./routes/api/v59.0/classes/[className].ts";
import * as $2 from "./routes/authorization/_middleware.ts";
import * as $3 from "./routes/authorization/token.ts";

const manifest = {
  routes: {
    "./routes/api/v59.0/_middleware.ts": $0,
    "./routes/api/v59.0/classes/[className].ts": $1,
    "./routes/authorization/_middleware.ts": $2,
    "./routes/authorization/token.ts": $3,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
